### ISSUE TITLE
[discussion] | Recommendations for acquiring a device

### ISSUE THREAD

**Issue by Ricky-Tigg** [iAnonymous3000/awesome-grapheneos-guide#2]
Hello. Regarding the **anonymity of the transaction**, avoiding that the IMEI of the phone is linked to the identity of the person who acquires it, is undoubtedly a recommendation to be observed. In this regard, could you let me know the underlying condition that puts the future owner of the phone in the position to observe it. Would this recommendation be somehow related to the recommendation to **make the acquisition in cash**?

**Comment by akc3n** [comment]
@Ricky-Tigg I hope this brief overview of how telecom networks work helps you better understand and answer your question.

Connect to a Cellular Network ➔ The SIM card identifies your subscription via the IMSI ➔ The radio identifies itself via the IMEI (as well as other IDs).

The IMSI (International Mobile Subscriber Identity) is the identifier of your SIM card (your subscriber ID). It is not hard-wired in the phone and can be changed by inserting a different SIM card. The IMSI is tied to your phone plan, and there is no limitation on changing it. The telecom network requires your IMSI to allow access to the network. This is fundamental to how telecom networks operate.

The IMEI is a hardware identifier. The cellular radio has multiple IMEIs (radio identifiers) that are part of the SoC and/or a separate radio, depending on the device. 

Side note: The IMEI is not supposed to be changeable. This is because modern radios do not support changing the IMEI through hardware or firmware.

> Would this recommendation be somehow related to the recommendation to make the acquisition in cash?

That all depends on ones threat model. If purchasing a second hand device, their carrier will have logs of that IMEI and when inserting a new SIM card on a different carrier, that IMEI may potentially be linked internally between those carriers. Although, I'm not able to provide specifics on how that intercommunication happens between said telecom network operators.

**Comment by Ricky-Tigg** [comment]
An escape from the underlying control of these technologies dedicated to identification being beyond the reach of anyone using a telephone dedicated to the cellular network, any foundation for the said assertion subject to the anonymity of the transaction seemed highly improbable. It was therefore not surprising to observe that any attempt to demonstrate that this could have been so was in vain. As it makes sense in the case of a telephone ready for use on a private cellular network, not only the telephone, but also the holder of the SIM card, are identifiable by the operator, and this, in a **transparent** manner. It was therefore worth closing this ticket so promptly, as there could be nothing to discuss against a misleading assertion.
